# Generated by Django 5.1.6 on 2025-02-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedcard', '0002_rename_weddingcard_wedding_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wedding_card',
            old_name='image',
            new_name='back_image',
        ),
        migrations.AddField(
            model_name='wedding_card',
            name='front_image',
            field=models.ImageField(blank=True, help_text='Upload JPG image for the wedding card', null=True, upload_to='wedding_cards/'),
        ),
        migrations.AddField(
            model_name='wedding_card',
            name='gsm',
            field=models.IntegerField(null=True),
        ),
    ]
