# Generated by Django 5.1.6 on 2025-02-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedcard', '0003_rename_image_wedding_card_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding_card',
            name='folding',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wedding_card',
            name='layer',
            field=models.IntegerField(null=True),
        ),
    ]
