# Generated by Django 5.1.6 on 2025-02-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedcard', '0004_wedding_card_folding_wedding_card_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding_card',
            name='back_image',
            field=models.ImageField(blank=True, help_text='Upload back JPG image for the wedding card', null=True, upload_to='wedding_cards/'),
        ),
        migrations.AlterField(
            model_name='wedding_card',
            name='front_image',
            field=models.ImageField(blank=True, help_text='Upload front JPG image for the wedding card', null=True, upload_to='wedding_cards/'),
        ),
    ]
