# Generated by Django 5.1.6 on 2025-03-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedcard', '0005_alter_wedding_card_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding_card',
            name='choice',
            field=models.CharField(choices=[('premium', 'PREMIUM'), ('general', 'GENERAL'), ('medium', 'MEDIUM')], default='premium', max_length=11),
        ),
    ]
