# Generated by Django 5.1.6 on 2025-03-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedcard', '0006_wedding_card_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding_card',
            name='details',
            field=models.TextField(help_text='Maximum 100 words', null=True),
        ),
    ]
