# Generated by Django 5.1.6 on 2025-03-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedcard', '0007_wedding_card_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding_card',
            name='minimum',
            field=models.IntegerField(null=True),
        ),
    ]
